COMMAND_REQUEST_ACTION = 0x0

COMMAND_ECHO = 0x1
COMMAND_WRITE_LCD = 0x2
COMMAND_CLEAR_LCD = 0x3
COMMAND_WRITE_STEREO = 0x4
COMMAND_ENTER_LOW_POWER_MODE = 0x5
COMMAND_CHANGE_COLOR_TEMPERATURE = 0x6
COMMAND_CHANGE_COLOR_CORRECTION = 0x7
COMMAND_CHANGE_LED_BRIGHTNESS = 0x8

COMMAND_INFO = 0x9

COMMAND_NO_OP = 0xA
